language:
  - python
python:
  - "2.7"
env:
  global:
    - secure: "7eKy4uX8FghBPYH7E0uysnJcV3BJpfv3YlL9rAJje62MqHdHpEHNpHrUelIoghmZXKY3CrjHMPfl6dBVr2WN5D4v3SR2r4KST+vc+dg6pvk5WuBq/20GQjNEEfQ+mBHVEwztIRgXloRdieMYJIKuo166UGhLbbLmrA/p+3+Ih6cHrP8ZJYztKrwkAuIjp9WovRuPl9S4vdD5/UM7OgJt/VnNC5M/l3hbqvLagDUQAlh+J0lE6ynE8+vvrX8lUHsRUhJgbZ+dn9XRHRub9bhqmwusOtpoGXp48hlOzpCLYgrwbSMeQCWq627bZkvaP9dooaDtgJCUlpdRm0+kXQhZ9xW2X9sNFq6GSsGopv8XMqy08BMKKBzk/Uk+nu91si5wYDeFVB3baxhhfTnIqcwruGamC1Mr5ObNeH7YLewrekxD7H3OSz24z8C+aHNkeamwM0uS9LnLY1FW2NZY5l2FYgOItfeYM5LA65VU4UUjqnCd9C7rl5mA9dcd4ywJ6x8C9i6bANusSlp10g6W1TwxZsxfKWy0XxcfsC+o9Hv5KgD3aPtRdVUiYtAXxKSlacHynIfTd+8//v7gkf92sZ5iR09jvtqmOgM+ppdgR77laYTS5nLyHo/Yolk3sL32cdg6buNxuSiDqzW4x+lQlrjmWx7eRMlm1eynzj+6JqZzmYQ="
script: source .travis.sh
sudo: required
after_success:
  - set +x
  - export GIT_COMMITTER_NAME=$GIT_NAME
  - export GIT_COMMITTER_EMAIL=$GIT_EMAIL
  - export GIT_AUTHOR_NAME=$GIT_NAME
  - export GIT_AUTHOR_EMAIL=$GIT_EMAIL
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then cd ~/;            fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git clone --branch gh-pages https://github.com/$TRAVIS_REPO_SLUG doc;  fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then cd doc;           fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then cp -r $TRAVIS_BUILD_DIR/_build/html ./; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then cp -r $TRAVIS_BUILD_DIR/_build/html-ja ./; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git status;                  fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git add -f .;                  fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git commit -m "Build documents from $TRAVIS_COMMIT" . ; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git remote -v; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git push --quiet https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git gh-pages; fi
